apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: airflow-eks
  region: ap-northeast-2
  version: '1.23'

iam:
  withOIDC: true
  
vpc:
  cidr: "10.1.0.0/16"
  nat:
    gateway:
      HighlyAvailable

managedNodeGroups:
- name: vos-nodegroup-1
  instanceType: t2.large
  instanceName: eks-worker-1
  desiredCapacity: 1
  minSize: 0
  maxSize: 6
  volumeSize: 50
  privateNetworking: true # True를 주면 private을 사용하게됨


- name: vos-nodegroup-2
  instanceType: c5.xlarge
  instanceName: eks-worker-2
  desiredCapacity: 0
  minSize: 0
  maxSize: 4
  volumeSize: 50
  privateNetworking: true
